#safe_cat_homepage:
#    path:     /
#    defaults: { _controller: SafeCatBundle:Default:index }
safe_cat_itembank:
    type: rest
    prefix: /v1
    resource: "Safe\CatBundle\Controller\ItemBankController"
    name_prefix:  api_1_item_banks # naming collision