services:
#    safe_cat.example:
#        class: Safe\CatBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    safe_cat.service.cat:
        class: Safe\CatBundle\Service\CATService
        arguments: ["@safe_cat.repository.itemBank"]
    safe_cat.repository.itemBank:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Safe\CatBundle\Entity\ItemBank        