<?php

namespace Safe\CatBundle\Repository;

/**
 * AbilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbilityRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function save($ability) {
        $em = $this->getEntityManager();
        $em->persist($ability);
        $em->flush();
        return $ability;
    }
    
    public function findOneAbility($examinee_code, $item_bank_code) {      
        $query = $this->createQueryBuilder('ability')
                                       ->join('ability.examinee', 'e')
                                       ->join('ability.itemBank', 'ib')
                                       ->where('e.code = :examinee_code')
                                       ->andWhere('ib.code = :item_bank_code')
                                       ->setParameter('examinee_code', $examinee_code)
                                       ->setParameter('item_bank_code', $item_bank_code)
                                       ->getQuery();
        
        return $query->getOneOrNullResult();
    }
}
