<?php

namespace Safe\CatBundle\Repository;

/**
 * ExamineeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamineeRepository extends \Doctrine\ORM\EntityRepository
{
}
