<?php
namespace Safe\CatBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ItemBankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemBankRepository extends EntityRepository
{

}
