<?php

namespace Safe\CatBundle\Repository;

/**
 * ItemBankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemBankRepository extends \Doctrine\ORM\EntityRepository
{
}
