<?php

namespace Safe\CatBundle\Repository;

/**
 * ItemResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemResultRepository extends \Doctrine\ORM\EntityRepository
{
    public function save($itemResult) {
        $em = $this->getEntityManager();
        $em->persist($itemResult);
        $em->flush();
        return $itemResult;
    }
}
