<?php

namespace Safe\CatBundle\Repository;

/**
 * PastAbilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PastAbilityRepository extends \Doctrine\ORM\EntityRepository
{
}
