<?php
namespace Safe\CatBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PastAbilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PastAbilityRepository extends EntityRepository
{

}
