<?php

namespace Safe\TemaBundle\Repository;

/**
 * ActividadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActividadRepository extends \Doctrine\ORM\EntityRepository
{
    public function crearOActualizar($actividad) {
        $em = $this->getEntityManager();
        $em->getConnection()->beginTransaction();
        try {            
            $em->persist($actividad);                 
            $em->flush();   
            $item = $actividad->getItem();
            $item->setCode($actividad->getId());
            $item->setEnabled($actividad->isHabilitado());
            $em->persist($item);
            $em->flush();       
            $em->getConnection()->commit();
         } catch (Exception $ex) {
            $em->getConnection()->rollback();            
            throw $ex;
        }
        return $actividad;
    }
}
