<?php

namespace Safe\TemaBundle\Repository;

/**
 * AlumnoConceptoEstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlumnoEstadoConceptoRepository extends \Doctrine\ORM\EntityRepository
{
    public function crearOActualizar($alumnoEstadoConcepto) {
        $em = $this->getEntityManager();
        $em->persist($alumnoEstadoConcepto);                 
        $em->flush();   
        return $alumnoEstadoConcepto;
    }
}
