<?php

namespace Safe\TemaBundle\Repository;

/**
 * AlumnoEstadoCursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlumnoEstadoCursoRepository extends \Doctrine\ORM\EntityRepository
{
     public function crearOActualizar($alumnoEstadoCurso) {
        $em = $this->getEntityManager();
        $em->persist($alumnoEstadoCurso);                 
        $em->flush();   
        return $alumnoEstadoCurso;
    }
}
