<?php

namespace Safe\TemaBundle\Repository;

/**
 * ConceptoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptoRepository extends \Doctrine\ORM\EntityRepository
{
    public function crearOActualizar($concepto) {
        $em = $this->getEntityManager();
        $em->getConnection()->beginTransaction();
        try {            
            if ($concepto->getId() != null) {
                $this->actualizarListaSucesoras($concepto, $em);
            }                               
            $em->persist($concepto);                     
            $em->flush();       
            $itemBank = $concepto->getItemBank();
            $itemBank->setCode($concepto->getId());            
            $em->persist($itemBank);
            $em->flush();       
            
            $em->getConnection()->commit();
         } catch (Exception $ex) {
            $em->getConnection()->rollback();            
            throw $ex;
        }
        return $concepto;
    }
    
    public function buscarSucesoras($concepto) {
        $query = $this->createQueryBuilder('concepto')
                 ->select('concepto')
                 ->join('concepto.predecesoras', 'p')
                 ->where('p = :predecesora')
                 ->setParameter('predecesora', $concepto)
                 ->getQuery();
         return $query->getResult();
    }
    
    protected function actualizarListaSucesoras($concepto, $em) {
        $sucesoras = $this->buscarSucesoras($concepto);
        $sucesorasAActualizar = array();
        
        foreach($sucesoras as $sucesora) {
            if (!$concepto->getSucesoras()->contains($sucesora)) {            
                $sucesorasAActualizar[] = $sucesora;
            }
        }        
        foreach($sucesorasAActualizar as $sucesoraAEliminarRelacion) {
            $sucesoraAEliminarRelacion->getPredecesoras()->removeElement($concepto);
            $em->persist($sucesoraAEliminarRelacion);            
        }
        return $concepto;
    }
}
