services:
#    safe_tema.example:
#        class: Safe\TemaBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    safe_tema.service.tema:
        class: Safe\TemaBundle\Service\TemaService
        arguments: ["@safe_tema.repository.tema"]       
    safe_tema.service.concepto:
        class: Safe\TemaBundle\Service\ConceptoService
        arguments: ["@safe_tema.repository.concepto"]       
    safe_tema.service.actividad:
        class: Safe\TemaBundle\Service\ActividadService
        arguments: ["@safe_tema.repository.actividad"]  
    safe_tema.repository.tema:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Safe\TemaBundle\Entity\Tema
    safe_tema.repository.concepto:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Safe\TemaBundle\Entity\Concepto           
    safe_tema.repository.actividad:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Safe\TemaBundle\Entity\Actividad          
    safe_tema.repository.alumno.tema.estado:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Safe\TemaBundle\Entity\AlumnoEstadoTema            
    safe_tema.form.type.identificador_tema:
        class: Safe\TemaBundle\Form\IdentificadorTemaType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
          - {name: form.type, alias: 'identificador_tema'}
    safe_tema.form.type.identificador_concepto:
        class: Safe\TemaBundle\Form\IdentificadorConceptoType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
          - {name: form.type, alias: 'identificador_concepto'}
            