services:
#    safe_tema.example:
#        class: Safe\TemaBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    safe_tema.repository.tema:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Safe\TemaBundle\Entity\Tema