<?php

namespace Safe\CursoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursoRepository extends EntityRepository
{
    public function crearOActualizar($curso) {
        $em = $this->getEntityManager();
        $em->persist($curso);            
        $em->flush();
        return $curso;
    }
}
