#parameters:
#    parameter_name: value
services:
#    safe_alumno.example:
#        class: Safe\AlumnoBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    safe_alumno.service.alumno:
        class: Safe\AlumnoBundle\Service\AlumnoService
        arguments: ["@safe_alumno.repository.alumno"]
    safe_alumno.service.curso_asignado:
        class: Safe\AlumnoBundle\Service\CursoAsignadoService
        arguments: ["@safe_curso.repository.curso"]
    safe_alumno.service.tema_asignado:
        class: Safe\AlumnoBundle\Service\TemaAsignadoService
        arguments: ["@safe_tema.repository.tema", "@safe_alumno.repository.alumno", "@safe_curso.repository.curso", "@safe_tema.repository.alumno.tema.estado", "@safe_tema.repository.alumno.curso.estado"]    
    safe_alumno.service.concepto_asignado:
        class: Safe\AlumnoBundle\Service\ConceptoAsignadoService
        arguments: ["@safe_tema.repository.concepto", "@safe_alumno.repository.alumno", "@safe_tema.repository.tema", "@safe_tema.repository.alumno.concepto.estado", "@safe_tema.repository.alumno.tema.estado"]  
    safe_alumno.service.actividad_asignada:
        class: Safe\AlumnoBundle\Service\ActividadAsignadaService
        arguments: ["@safe_tema.repository.actividad", "@safe_alumno.repository.alumno", "@safe_tema.repository.concepto", "@safe_tema.repository.alumno.concepto.estado", "@safe_cat.service.cat"]     
    safe_alumno.repository.alumno:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Safe\AlumnoBundle\Entity\Alumno
    safe_alumno.form.type.identificador_alumno:
        class: Safe\AlumnoBundle\Form\IdentificadorAlumnoType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
          - {name: form.type, alias: 'identificador_alumno'}