safe_docente:
    type: rest
    prefix: /v1
    resource: "Safe\DocenteBundle\Controller\DocenteController"
    name_prefix:  api_1_docentes # naming collision
safe_docente_curso:
    type: rest
    parent:   safe_docente
    resource: "Safe\DocenteBundle\Controller\CursoImpartidoController"
    name_prefix:  api_1_docentes_cursos # naming collision
safe_docente_curso_tema:
    type: rest
    parent:   safe_docente_curso
    resource: "Safe\DocenteBundle\Controller\TemaImpartidoController"
    name_prefix:  api_1_docentes_cursos_temas # naming collision
safe_docente_curso_tema_concepto:
    type: rest
    parent:   safe_docente_curso_tema
    resource: "Safe\DocenteBundle\Controller\ConceptoImpartidoController"
    name_prefix:  api_1_docentes_cursos_temas_conceptos # naming collision
    