safe_docente_homepage:
    path:     /docente/home
    defaults: { _controller: SafeDocenteBundle:Default:index }
safe_docente:
    type: rest
    prefix: /v1
    resource: "Safe\DocenteBundle\Controller\DocenteController"
    name_prefix:  api_1_docentes # naming collision
safe_docente_curso:
    type: rest
    parent:   safe_docente
    resource: "Safe\DocenteBundle\Controller\CursoImpartidoController"
    name_prefix:  api_1_docentes_cursos # naming collision
    