services:
#    safe_docente.example:
#        class: Safe\DocenteBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    safe_docente.service.docente:
        class: Safe\DocenteBundle\Service\DocenteService
        arguments: ["@safe_docente.repository.docente"]
    safe_docente.repository.docente:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Safe\DocenteBundle\Entity\Docente
