services:
#    safe_docente.example:
#        class: Safe\DocenteBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    safe_docente.service.docente:
        class: Safe\DocenteBundle\Service\DocenteService
        arguments: ["@safe_docente.repository.docente"]
    safe_docente.service.curso_impartido:
        class: Safe\DocenteBundle\Service\CursoImpartidoService
        arguments: ["@safe_curso.repository.curso"]   
    safe_docente.service.tema_impartido:
        class: Safe\DocenteBundle\Service\TemaImpartidoService
        arguments: ["@safe_tema.repository.tema"]       
    safe_docente.service.concepto_impartido:
        class: Safe\DocenteBundle\Service\ConceptoImpartidoService
        arguments: ["@safe_tema.repository.concepto", "@safe_cat.service.cat"]               
    safe_docente.service.actividad_impartida:
        class: Safe\DocenteBundle\Service\ActividadImpartidaService
        arguments: ["@safe_tema.repository.actividad", "@safe_cat.service.cat"]                       
    safe_docente.repository.docente:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Safe\DocenteBundle\Entity\Docente
    safe_docente.form.type.identificador_docente:
        class: Safe\DocenteBundle\Form\IdentificadorDocenteType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
          - {name: form.type, alias: 'identificador_docente'}
    safe_docente.form.type.registracion.tema:
            class: Safe\DocenteBundle\Form\RegistracionTemaType
            arguments: ["@doctrine.orm.entity_manager"]
            tags:
                - { name: form.type }
    safe_docente.form.type.registracion.concepto:
            class: Safe\DocenteBundle\Form\RegistracionConceptoType
            arguments: ["@doctrine.orm.entity_manager"]
            tags:
                - { name: form.type }            
    safe_docente.form.type.registracion.concepto.form:
            class: Safe\DocenteBundle\Form\RegistracionConceptoFormType
            arguments: ["@doctrine.orm.entity_manager"]
            tags:
                - { name: form.type }                        