safe_perfil:
    resource: "@SafePerfilBundle/Resources/config/routing.yml"
    prefix:   /api
    type: rest

safe_tema:
    resource: "@SafeTemaBundle/Resources/config/routing.yml"
    prefix:   /

safe_curso:
    resource: "@SafeCursoBundle/Resources/config/routing.yml"
    prefix:   /

safe_docente:
    resource: "@SafeDocenteBundle/Resources/config/routing.yml"
    prefix:   /api
    type: rest

safe_alumno:
    resource: "@SafeAlumnoBundle/Resources/config/routing.yml"
    prefix:   /api
    type: rest

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#hwi_oauth_security:
#    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#    prefix: /login
    
#hwi_oauth_redirect:
#    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#    prefix:   /login

#hwi_oauth_login:
#    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#    prefix:   /login
#hwi_oauth_connect:
#    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
#    prefix:   /login
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#    prefix: /logout
logout:
    path: /logout
#google_login:
#    path: /login/check-google 