#parameters:
#    parameter_name: value
services:
#    safe_estudiante.example:
#        class: Safe\EstudianteBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    safe_estudiante.service.estudiante:
        class: Safe\EstudianteBundle\Service\EstudianteService
        arguments: ["@safe_estudiante.repository.estudiante"]
    safe_estudiante.repository.estudiante:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Safe\EstudianteBundle\Entity\Estudiante
