safe_admin_homepage:
    path:     /admin/home
    defaults: { _controller: SafeAdminBundle:Default:index }
safe_admin_docentes:
    type: rest
    prefix: /v1/admin
    resource: "Safe\AdminBundle\Controller\DocenteController"
    name_prefix:  api_1_admin_docentes # naming collision
safe_admin_institutos:
    type: rest
    prefix: /v1/admin
    resource: "Safe\AdminBundle\Controller\InstitutoController"
    name_prefix:  api_1_admin_institutos # naming collision    
safe_admin_alumnos:
    type: rest
    prefix: /v1/admin
    resource: "Safe\AdminBundle\Controller\AlumnoController"
    name_prefix:  api_1_admin_alumnos # naming collision
safe_admin_cursos:
    type: rest
    prefix: /v1/admin
    resource: "Safe\AdminBundle\Controller\CursoController"
    name_prefix:  api_1_admin_cursos # naming collision
safe_admin_cursos_alumnos:
    type: rest
    parent:   safe_admin_cursos
    resource: "Safe\AdminBundle\Controller\CursoAlumnoController"
    name_prefix:  api_1_admin_cursos_alumnos # naming collision
safe_admin_cursos_docentes:
    type: rest
    parent:   safe_admin_cursos
    resource: "Safe\AdminBundle\Controller\CursoDocenteController"
    name_prefix:  api_1_admin_cursos_docentes # naming collision
safe_admin_tipo_documentos:
    type: rest
    prefix: /v1/admin
    resource: "Safe\AdminBundle\Controller\TipoDocumentoController"
    name_prefix:  api_1_admin_tipo_documentos # naming collision