services:
#    safe_admin.example:
#        class: Safe\AdminBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    safe_admin.form.type.registracion.curso:
            class: Safe\AdminBundle\Form\RegistracionCursoType
            arguments: ["@doctrine.orm.entity_manager"]
            tags:
                - { name: form.type }