parameters:
    safe_user_provider.class: Safe\PerfilBundle\Core\User\FOSUBUserProvider
services:
#    safe_perfil.example:
#        class: Safe\PerfilBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    safe_user_provider:
        class: "%safe_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager, {google: googleId}]