<?php

namespace Safe\AlumnoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlumnoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlumnoRepository extends EntityRepository
{
    
    public function crearOActualizar($alumno) {
        $em = $this->getEntityManager();
        $em->getConnection()->beginTransaction();
        
        try {
            $em->persist($alumno->getUsuario());
            $em->persist($alumno);            
            $em->flush();
            $em->getConnection()->commit();
        } catch (Exception $ex) {
            $em->getConnection()->rollback();            
            throw $ex;
        }
    }
}
