<?php

namespace Safe\AlumnoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlumnoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Safe\CatBundle\Entity\Examinee;
class AlumnoRepository extends EntityRepository
{
    
    public function crearOActualizar($alumno) {
        $em = $this->getEntityManager();
        $em->getConnection()->beginTransaction();
        
        try {
            $createExaminee = false;
            if ($alumno->getId() === null) {
                $createExaminee = true;
            }     
            
            $em->persist($alumno->getUsuario());
            $em->persist($alumno);            
            $em->flush();
            if ($createExaminee) {
                $examinee = new Examinee();
                $examinee->setCode($alumno->getId());
                $em->persist($examinee);            
                $em->flush();
            }
            
            $em->getConnection()->commit();
        } catch (Exception $ex) {
            $em->getConnection()->rollback();            
            throw $ex;
        }
    }
}
