<?php

namespace Safe\PerfilBundle\Repository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function save($usuario) {
        $em = $this->getEntityManager();
        $em->persist($usuario);
        $em->flush();
        return $usuario;
    }
    
    public function registrarUsuario($usuario, $docente, $alumno) {
        $em = $this->getEntityManager();
        $em->getConnection()->beginTransaction();
        
        try {
            $em->persist($usuario);
            if (isset($docente)) {
                $docente->setUsuario($usuario);
                $em->persist($docente);
            }
            if (isset($alumno)) {
                $alumno->setUsuario($usuario);
                $em->persist($alumno);
            }
            $em->flush();
            $em->getConnection()->commit();
        } catch (Exception $ex) {
            $em->getConnection()->rollback();
            throw $ex;
        }
    }
}
