services:
#    safe_core.example:
#        class: Safe\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    safe_api.event.authentication_success_listener:
        class: Safe\CoreBundle\EventListener\AuthenticationSuccessListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }