FOS\UserBundle\Model\User:
#    exclusion_policy: ALL
#FOS\UserBundle\Entity\User:
    exclusion_policy: ALL
    properties:
        username:
            expose: true
        email:
            expose: true
        lastLogin:
            expose: true
        enabled:
            expose: true
        locked:
            expose: true
        roles:
            expose: true
        credentialsExpired:
            expose: true
        credentialsExpireAt:
            expose: true
#            groups: [admin_listado]        