FOS\UserBundle\Model\User:
#    exclusion_policy: ALL
#FOS\UserBundle\Entity\User:
    exclusion_policy: ALL
    properties:
        email:
            expose: true
            groups: [listado]
        lastLogin:
            expose: true
            groups: [listado]            
        enabled:
            expose: true
            groups: [admin_listado]
        locked:
            expose: true
            groups: [admin_listado]
        roles:
            expose: true
            groups: [admin_listado]    
        credentialsExpired:
            expose: true
            groups: [admin_listado]
        credentialsExpireAt:
            expose: true
            groups: [admin_listado]        