<?php

namespace Safe\InstitutoBundle\Repository;

/**
 * InstitutoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitutoRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function crearOActualizar($instituto) {
        $em = $this->getEntityManager();
        $em->persist($instituto);            
        $em->flush();
        return $instituto;
    }
}
